In [18]:
import torch
import numpy as np

In [32]:
# arange与numpy中同名函数的功能相同
x = torch.arange(12, dtype=torch.float32)
print(x, x * 4)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44.])


In [20]:
x.shape

torch.Size([12])

In [21]:
x.numel()

12

`reshape`和`numpy`同名函数功能相同
使用`-1`可以自动计算剩余的维度

In [22]:
X = x.reshape(3, 4)
Y = x.reshape(3, -1)
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

和`numpy`一样，我们可以使用`zeros`和`ones`来创建数组，可以使用`randn`创建独立同标准正态分布的数组。

同理还有`zeros_like`，`ones_like`，创建同形的张量。

In [23]:
a = torch.zeros((2, 3))
b = torch.ones((4, 5))
r = torch.randn((3, 4))
c = torch.zeros_like(r)
a, b, r, c

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[ 1.3868,  0.1643, -0.2282, -0.1567],
         [ 1.2685, -0.3019,  0.0530, -0.7788],
         [ 1.5094,  1.7890,  0.6588,  0.6313]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

## 数组的运算

数组的运算和`numpy`一样，可以使用正常的符号表示按元素计算。

In [34]:
x = torch.tensor([1, 2, 4, 8])
y = torch.from_numpy(np.full(4, 2))
x + y, x * y, x ** y

(tensor([ 3,  4,  6, 10]), tensor([ 2,  4,  8, 16]), tensor([ 1,  4, 16, 64]))

In [35]:
x * 3, x + 1, x / 2

(tensor([ 3,  6, 12, 24]),
 tensor([2, 3, 5, 9]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]))

指数函数、三角函数可以正常使用

In [25]:
torch.exp(x), torch.sin(x), torch.sinh(x)

(tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]),
 tensor([ 0.8415,  0.9093, -0.7568,  0.9894]),
 tensor([1.1752e+00, 3.6269e+00, 2.7290e+01, 1.4905e+03]))

满足一定条件的张量可以进行拼接(concatenate two tensors together)

使用`cat`可以将张量进行拼接，使用`dim`参数可以指定拼接的维度。`dim=0`表示行拼接，拼接所得的数组行数等于两行之和；`dim=1`同理表示列拼接。

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[4.0, 3, 1, 2], [4, 3, 2 ,1], [1, 2, 3, 4]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[4., 3., 1., 2.],
         [4., 3., 2., 1.],
         [1., 2., 3., 4.]]))

In [27]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 4.,  3.,  1.,  2.],
         [ 4.,  3.,  2.,  1.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  3.,  1.,  2.],
         [ 4.,  5.,  6.,  7.,  4.,  3.,  2.,  1.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]))

两个同行数组可以按位比较

In [28]:
X > Y, X == Y

(tensor([[False, False,  True,  True],
         [False,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False, False, False, False],
         [ True, False, False, False],
         [False, False, False, False]]))

使用`.sum()`可以求和，同`.numel()`表示取出元素数

但注意`.sum()`的结果是一个一维张量

In [29]:
X.sum(), X.numel(), type(X.sum())

(tensor(66.), 12, torch.Tensor)

## `numpy.ndarray`和`torch.tensor`的转换

使用`A.numpy()`可以将张量`A`转换为数组，使用`torch.from_numpy(B)`可以将数组`B`转换为张量

使用`a.item()`，`float(a)`还可以直接将零维张量转化为`Python`内置类型（只有单元素张量可以用`.item()`转换）

In [31]:
a = torch.tensor([3.5])
b = torch.tensor([4, 5, 6])
a.item()

3.5

## 2.1.8 Exercise