In [1]:
import torch
import numpy as np

In [2]:
A = torch.arange(20).reshape(5, 4)
# A.clone() 会创建A的深拷贝
B = A.clone()
A, id(A) == id(B)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 False)

In [3]:
A, A.T, A + B, A * B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225],
         [256, 289, 324, 361]]))

In [4]:
a = 2
X = torch.arange(24).reshape((2, 3, 4))
a + X, a * X

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

对`A`求平均值要求为`float`类型，需要先用`.float`进行一次转换。

In [5]:
A, A.sum(), A.sum(dim=0), A.sum(dim=1), A.float().mean(), A.sum() / A.numel()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor(190),
 tensor([40, 45, 50, 55]),
 tensor([ 6, 22, 38, 54, 70]),
 tensor(9.5000),
 tensor(9.5000))

同样有行分块求平均`A.mean(dim=0)`（各列相加除以列高，也就是行分块后求平均）。

列分块求和求平均，求和结果可以继续**保留列向量**。

In [6]:
A.float().mean(axis=0), A.sum(axis=0) / A.shape[0], A.float().mean(axis=1), A.sum(axis=1) / A.shape[1], A.float().mean(axis=1, keepdim=True)

(tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([[ 1.5000],
         [ 5.5000],
         [ 9.5000],
         [13.5000],
         [17.5000]]))

点乘：不可像`numpy`那样直接使用`dot`或者`@`

矩阵向量乘法：像`numpy`一样，向量自动升维到列向量，可以用`torch.mv()`或`@`

In [7]:
x = torch.arange(4)
y = torch.ones(4)
x, y, torch.sum(x * y)

(tensor([0, 1, 2, 3]), tensor([1., 1., 1., 1.]), tensor(6.))

In [8]:
A, x, A @ x, torch.mv(A, x)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([0, 1, 2, 3]),
 tensor([ 14,  38,  62,  86, 110]),
 tensor([ 14,  38,  62,  86, 110]))

In [9]:
C = torch.ones(4, 3).long()
A @ C, torch.mm(A, C)

(tensor([[ 6,  6,  6],
         [22, 22, 22],
         [38, 38, 38],
         [54, 54, 54],
         [70, 70, 70]]),
 tensor([[ 6,  6,  6],
         [22, 22, 22],
         [38, 38, 38],
         [54, 54, 54],
         [70, 70, 70]]))

范数：使用`torch.norm`获取向量的Euclid范数，或矩阵的Frobenius范数，两者均为各元素的平方和。

In [10]:
torch.norm(x.float()), torch.norm(A.float())

(tensor(3.7417), tensor(49.6991))

总结：
张量的深拷贝：`A.clone()`
各行求和：`A.sum(dim=0)`
求平均：`A.mean()`
矩阵向量乘法：`torch.mv(M, v)`
矩阵乘法：`torch.mv(A, B)`
向量和矩阵的范数：`torch.norm(v)`