In [2]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
x.grad

In [5]:
y = 2 * x @ x
y

tensor(28., grad_fn=<DotBackward0>)

In [6]:
y.backward()
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([ 0.,  4.,  8., 12.]))

In [7]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
def f(a):
    b = a *2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [9]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [10]:
a.grad, a.grad == d / a

(tensor(409600.), tensor(True))

In [13]:
x.grad.zero_()
x.reshape((-1, 1))
a = torch.tensor([[1, 2, -1, 2], [-1, -3, 4, 6], [0, 8, 6, 5], [-5, -4, 2, 3]], dtype=torch.float32)
y = x.T @ a @ x
y.backward()
x.grad, x.grad == (a + a.T) @ x

(tensor([-10.,  24.,  57.,  34.]), tensor([True, True, True, True]))