In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):
    # A PyTorch data iterator.
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter)), data_iter

([tensor([[-1.0218, -1.0930],
          [ 0.6999, -0.1982],
          [-0.8999, -0.4899],
          [ 0.0293, -0.6425],
          [ 0.0588,  1.0240],
          [-0.5778,  0.0972],
          [-0.4357, -0.1299],
          [-1.7230, -1.8514],
          [-0.5346, -1.1519],
          [-0.0422,  0.7369]]),
  tensor([[5.8834],
          [6.2717],
          [4.0556],
          [6.4520],
          [0.8469],
          [2.6995],
          [3.7647],
          [7.0336],
          [7.0294],
          [1.6009]])],
 <torch.utils.data.dataloader.DataLoader at 0x258bf260910>)

## 定义模型

了解如何手动定义模型是十分必要的，但是复杂的模型往往借助线程的框架来定义。

神经网络在`PyTorch`中可以通过`nn`引入，`nn`是`neural network`的缩写。

全连接层通过`nn.Linear`实现。

In [5]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

使用`.data.normal_`以正态分布的方式初始化参数，`.data.fill_`将初始化参数填充为某个向量（如全零向量）

In [6]:
# Initialize the parameters
# Just need to use the predefined way in pytorch

net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

定义平方误差函数只需要引入`nn.MSELoss()`即可。

In [7]:
loss = nn.MSELoss()

定义优化算法

In [8]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

开始训练

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for x, y in data_iter:
        # net(x) can generate the prediction of x.
        l = loss(net(x), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000200
epoch 2, loss 0.000106
epoch 3, loss 0.000107


In [10]:
w = net[0].weight.data
b = net[0].bias.data

w, true_w, b, true_b

(tensor([[ 2.0002, -3.4000]]),
 tensor([ 2.0000, -3.4000]),
 tensor([4.1991]),
 4.2)